
name: publishtopsgallery

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh
        run: |
          Import-Module .\PSCredVault.psd1 -verbose
          Publish-Module -Path .\ -NuGetApiKey $env:NUGET_KEY -Verbose
