
name: publishtopsgallery

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh
        run: |
          pwd
          get-childitem
          Write-Output "Would use key for $($env:NUGET_KEY)"
